/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jiemian;

import Dao.Corders;
import Dao.Customers;
import Dao.Daoproxy;
import Dao.Orders;
import Dao.Product;
import Dao.Sellers;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zero
 */
public class Cmain extends javax.swing.JFrame {

    /**
     * Creates new form Cmain
     */
   Login parent;
    int id;
    String password;
    Daoproxy daoproxy;
    Customers customers;
    List<Corders> all = null ;
    public void setconf(Login _parent, int _id, Daoproxy _daoproxy){
        id = _id;
        parent = _parent;
        daoproxy = _daoproxy;
        password = this.parent.password;
        
    }
    public Cmain() {
        initComponents();
        this.jPanel_Product.setVisible(true);
        this.jPanel_Order.setVisible(false);
        //int _cid, String _cname, String _phonenum, String _sex, int _age, String _password) {
        
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();// 设置table内容居中
        // tcr.setHorizontalAlignment(JLabel.CENTER);
        tcr.setHorizontalAlignment(SwingConstants.CENTER);// 这句和上句作用一样
        C_query_jTable.setDefaultRenderer(Object.class, tcr);
        C_query_jTable1.setDefaultRenderer(Object.class, tcr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        popupMenu1 = new java.awt.PopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        C_jToggleButton_sort = new javax.swing.JToggleButton();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel_Product = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        L_Price = new javax.swing.JLabel();
        C_jTextField_pmin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        C_jTextField_pmax = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        C_jTextField_pname = new javax.swing.JTextField();
        jLabel_Pname = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_Pname1 = new javax.swing.JLabel();
        C_jTextField_pid = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        C_jButton_search = new javax.swing.JButton();
        C_jComboBox_sort = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        C_query_jTable = new javax.swing.JTable();
        jPanel_Order = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        L_Price1 = new javax.swing.JLabel();
        C_jTextField_pmin1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        C_jTextField_pmax1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        C_jTextField_pname1 = new javax.swing.JTextField();
        jLabel_Pname2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel_Pname3 = new javax.swing.JLabel();
        C_jTextField_pid1 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        C_jButton_clear1 = new javax.swing.JButton();
        C_jButton_search1 = new javax.swing.JButton();
        C_jComboBox_sort1 = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        C_jLabel_Oid = new javax.swing.JLabel();
        C_jTextField_oid1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        C_query_jTable1 = new javax.swing.JTable();
        jPanel_Menu = new javax.swing.JPanel();
        C_jButton_product = new javax.swing.JButton();
        C_jButton_einfo = new javax.swing.JButton();
        C_jButton_Order = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        popupMenu1.setLabel("popupMenu1");
        popupMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupMenu1ActionPerformed(evt);
            }
        });

        C_jToggleButton_sort.setText("价格由高到低");
        C_jToggleButton_sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_jToggleButton_sortActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel12.setLayout(new javax.swing.OverlayLayout(jPanel12));

        L_Price.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        L_Price.setText("价格:");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-");

        C_jTextField_pmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_jTextField_pmaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(L_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C_jTextField_pmin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jTextField_pmax, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_jTextField_pmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_jTextField_pmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {C_jTextField_pmax, C_jTextField_pmin, L_Price, jLabel1});

        jLabel_Pname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Pname.setText("商品名:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Pname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jTextField_pname, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Pname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(C_jTextField_pname))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Pname1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Pname1.setText("商品id:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Pname1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C_jTextField_pid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Pname1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_jTextField_pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton4.setText("清零");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        C_jButton_search.setText("搜索");
        C_jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_jButton_searchActionPerformed(evt);
            }
        });

        C_jComboBox_sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "价格从低到高", "价格从高到低", "销量从低到高", "销量从高到低" }));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(C_jComboBox_sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jButton_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(C_jButton_search)
                    .addComponent(C_jComboBox_sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        C_query_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "商品id", "商品", "价格", "数量", "说明", "卖家", "销量"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        C_query_jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C_query_jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(C_query_jTable);

        javax.swing.GroupLayout jPanel_ProductLayout = new javax.swing.GroupLayout(jPanel_Product);
        jPanel_Product.setLayout(jPanel_ProductLayout);
        jPanel_ProductLayout.setHorizontalGroup(
            jPanel_ProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProductLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel_ProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel_ProductLayout.setVerticalGroup(
            jPanel_ProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ProductLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.add(jPanel_Product);

        L_Price1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        L_Price1.setText("价格:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-");

        C_jTextField_pmax1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_jTextField_pmax1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(L_Price1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jTextField_pmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jTextField_pmax1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(L_Price1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(C_jTextField_pmin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(C_jTextField_pmax1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel_Pname2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Pname2.setText("商品名:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel_Pname2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C_jTextField_pname1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_jTextField_pname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Pname2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Pname3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Pname3.setText("商品id:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Pname3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jTextField_pid1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Pname3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_jTextField_pid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        C_jButton_clear1.setText("清零");
        C_jButton_clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_jButton_clear1ActionPerformed(evt);
            }
        });

        C_jButton_search1.setText("搜索");
        C_jButton_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_jButton_search1ActionPerformed(evt);
            }
        });

        C_jComboBox_sort1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "价格从低到高", "价格从高到低", "销量从低到高", "销量从高到低" }));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(C_jComboBox_sort1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jButton_clear1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jButton_search1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_jButton_clear1)
                    .addComponent(C_jButton_search1)
                    .addComponent(C_jComboBox_sort1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        C_jLabel_Oid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        C_jLabel_Oid.setText("订单号:");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(C_jLabel_Oid, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jTextField_oid1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_jLabel_Oid, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_jTextField_oid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        C_query_jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "订单号", "商品id", "商品", "价格", "数量", "卖家", "总价"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        C_query_jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C_query_jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(C_query_jTable1);

        javax.swing.GroupLayout jPanel_OrderLayout = new javax.swing.GroupLayout(jPanel_Order);
        jPanel_Order.setLayout(jPanel_OrderLayout);
        jPanel_OrderLayout.setHorizontalGroup(
            jPanel_OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_OrderLayout.createSequentialGroup()
                .addGroup(jPanel_OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_OrderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 36, Short.MAX_VALUE))
        );
        jPanel_OrderLayout.setVerticalGroup(
            jPanel_OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_OrderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.add(jPanel_Order);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        C_jButton_product.setText("查询商品");
        C_jButton_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_jButton_productActionPerformed(evt);
            }
        });

        C_jButton_einfo.setText("我的资料");
        C_jButton_einfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_jButton_einfoActionPerformed(evt);
            }
        });

        C_jButton_Order.setText("我的订单");
        C_jButton_Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_jButton_OrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_MenuLayout = new javax.swing.GroupLayout(jPanel_Menu);
        jPanel_Menu.setLayout(jPanel_MenuLayout);
        jPanel_MenuLayout.setHorizontalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(C_jButton_product)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(C_jButton_Order)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(C_jButton_einfo)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel_MenuLayout.setVerticalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_jButton_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_jButton_product, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_jButton_einfo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popupMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popupMenu1ActionPerformed

    private void C_jToggleButton_sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_jToggleButton_sortActionPerformed
        // TODO add your handling code here:
        String sorttype;
        sorttype = C_jToggleButton_sort.getText();
        if(sorttype.equals("价格由低到高"))
        {
            C_jToggleButton_sort.setText("价格由高到低");
        }
        else{
                C_jToggleButton_sort.setText("价格由低到高");
        }
    }//GEN-LAST:event_C_jToggleButton_sortActionPerformed

    private void C_jButton_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_jButton_productActionPerformed
        // TODO add your handling code here:
        this.jPanel_Product.setVisible(true);
        this.jPanel_Order.setVisible(false);
    }//GEN-LAST:event_C_jButton_productActionPerformed

    private void C_jButton_OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_jButton_OrderActionPerformed
        // TODO add your handling code here:
        this.jPanel_Product.setVisible(false);
        this.jPanel_Order.setVisible(true);
    }//GEN-LAST:event_C_jButton_OrderActionPerformed

    private void C_jTextField_pmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_jTextField_pmaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_jTextField_pmaxActionPerformed

    private void C_jButton_einfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_jButton_einfoActionPerformed
        // TODO add your handling code here:
        Information editinfo = new Information();
        try {
            customers = daoproxy.findCustomers(id, customers.password);
        } catch (Exception ex) {
            Logger.getLogger(Smain.class.getName()).log(Level.SEVERE, null, ex);
            String message = ex.getMessage();
            int index = message.lastIndexOf(')');
            message = message.substring(index+1);
            JOptionPane.showMessageDialog(this, message);
            return ;
        }

        //Daoproxy _daoproxy, int _id, String _oldname, String _oldsex, String _oldphonenum, String _oldpassword, String _usrtype, int _oldage){
        try{
            editinfo.setconf(daoproxy, id, customers.cname,customers.sex, customers.phonenum, customers.password, "消费者", customers.age,customers,null);
        }catch(Exception ex){
                 Logger.getLogger(Smain.class.getName()).log(Level.SEVERE, null, ex);
            String message = ex.getMessage();
            int index = message.lastIndexOf(')');
            message = message.substring(index+1);
            JOptionPane.showMessageDialog(this, message);
                }
        editinfo.setVisible(true);
    }//GEN-LAST:event_C_jButton_einfoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        C_jTextField_pid.setText("");
        C_jTextField_pmax.setText("");
        C_jTextField_pmin.setText("");
        C_jTextField_pname.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

       public void initsearch(){
           this.C_jButton_searchActionPerformed(null);
       }
        public void initsearchO(){
           this. C_jButton_search1ActionPerformed(null);
       }
    private void C_jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_jButton_searchActionPerformed
        // TODO add your handling code here:
        String keyword = C_jTextField_pname.getText().trim();
        String str_min = C_jTextField_pmin.getText().trim();
        String str_max = C_jTextField_pmax.getText().trim();
        String str_pid = C_jTextField_pid.getText().trim();
        String sorttype = (String)C_jComboBox_sort.getSelectedItem();
        sorttype = sorttype.trim();
        double minprice = 0, maxprice = 1e10;
        int pid = 0;
        try{
            if(str_min.length()>0)
                minprice = Double.valueOf(str_min);
            if(str_max.length()>0)
                maxprice = Double.valueOf(str_max);
            if(str_pid.length()>0)
                pid = Integer.valueOf(str_pid);
        }catch(Exception ex){
            String message = ex.getMessage();
            int index = message.lastIndexOf(')');
            message = message.substring(index+1);
            JOptionPane.showMessageDialog(this, message+"\n请重新输入");
            return;
        }
        if(minprice < 0){
            minprice = 0;
            str_min = "0";
            C_jTextField_pmin.setText(str_min);
        }
        if(minprice > maxprice){
            str_max = "";
            C_jTextField_pmax.setText(str_max);
        }
        
        String sql = "select pid,pname,P.sid,price,comment,num,S.sname,P.sellnum FROM Product P, Sellers S WHERE P.sid = S.sid";
        if(keyword.length() > 0) {
            sql = sql + " and pname LIKE '%" + keyword + "%'"; 
        }
        if(str_min.length() > 0){
            sql = sql + " and price >= " + minprice;
        }
        if(str_max.length() > 0){
            sql = sql + "and price <=" + maxprice;
        }
        if(str_pid.length() > 0){
            sql = sql + " and pid = " + pid;
        }
        if(sorttype.equals("价格从低到高")){
            sql = sql + " order by price ASC";
        }else if(sorttype.equals("价格从高到低")) {
             sql = sql + " order by price DESC";
        }else if(sorttype.equals("销量从低到高")) {
             sql = sql + " order by  P.sellnum ASC";
        }else if(sorttype.equals("销量从高到低")) {
             sql = sql + " order by  P.sellnum DESC";
        }
        List<Product> all = null ;
        try {
            all = this.daoproxy.findProduct(sql);
        } catch (Exception ex) {
            String message = ex.getMessage();
            int index = message.lastIndexOf(')');
            message = message.substring(index+1);
            JOptionPane.showMessageDialog(this, message+"\n请重新输入");
            return;
        }
        
        //
        DefaultTableModel dtm = (DefaultTableModel)C_query_jTable.getModel();
        int row = dtm.getRowCount();
        for(int i = 0; i < row; ++i){
            dtm.removeRow(0);
        }
        row = all.size();
        for(int i = 0; i < row; ++i){
           Object[]rowData = {
               all.get(i).pid,
               all.get(i).pname,
               all.get(i).price,
               all.get(i).num,
               all.get(i).comment,
               all.get(i).sname,
               all.get(i).sellnum
           };

           dtm.addRow(rowData);
        }
    }//GEN-LAST:event_C_jButton_searchActionPerformed

    private void C_query_jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C_query_jTableMouseClicked
        // TODO add your handling code here:
        int row = C_query_jTable.getSelectedRow();
        int pid =(int) C_query_jTable.getValueAt(row,0);
        String pname = (String) C_query_jTable.getValueAt(row,1);
        double price = (double)C_query_jTable.getValueAt(row,2);
        int num = (int)C_query_jTable.getValueAt(row,3);
        String comment = (String)C_query_jTable.getValueAt(row,4);
    //    int _pid, String _pname, int _sid, double _price, String _comment, int _num)
        Product product;
        product = new Product(pid,pname,id,price,comment,num,null,0);
        BuyProduct buyProduct = new BuyProduct();
        buyProduct.setconf(this, product);
        buyProduct.setVisible(true);
    }//GEN-LAST:event_C_query_jTableMouseClicked

    private void C_jTextField_pmax1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_jTextField_pmax1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_jTextField_pmax1ActionPerformed

    private void C_jButton_clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_jButton_clear1ActionPerformed
        // TODO add your handling code here:
        C_jTextField_pname1.setText("");
         C_jTextField_oid1.setText("");
         C_jTextField_pmin1.setText("");
         C_jTextField_pmax1.setText("");
         C_jTextField_pid1.setText("");
         C_jComboBox_sort1.setSelectedIndex(0);
    }//GEN-LAST:event_C_jButton_clear1ActionPerformed

    private void C_jButton_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_jButton_search1ActionPerformed
        // TODO add your handling code here:
        String keyword = C_jTextField_pname1.getText().trim();
        String str_oid = C_jTextField_oid1.getText().trim();
        String str_min = C_jTextField_pmin1.getText().trim();
        String str_max = C_jTextField_pmax1.getText().trim();
        String str_pid = C_jTextField_pid1.getText().trim();
        String sorttype = (String)C_jComboBox_sort1.getSelectedItem();
        sorttype = sorttype.trim();
        double minprice = 0, maxprice = 1e10;
        int pid = 0;
        int oid = 0;
        try{
            if(str_min.length()>0)
                minprice = Double.valueOf(str_min);
            if(str_max.length()>0)
                maxprice = Double.valueOf(str_max);
            if(str_pid.length()>0)
                pid = Integer.valueOf(str_pid);
            if(str_oid.length()>0)
                oid = Integer.valueOf(str_oid);
        }catch(Exception ex){
            String message = ex.getMessage();
            int index = message.lastIndexOf(')');
            message = message.substring(index+1);
            JOptionPane.showMessageDialog(this, message+"\n请重新输入");
            return;
        }
        if(minprice < 0){
            minprice = 0;
            str_min = "0";
            C_jTextField_pmin.setText(str_min);
        }
        if(minprice > maxprice){
            str_max = "";
            C_jTextField_pmax.setText(str_max);
        }
     //   int _oid, int _pid, String _pname, int _sid,  double _price, int _buynum, String _sname, int _lastnum,double _sum
        String sql = "select oid,P.pid,pname,P.sid,price,O.num,S.sname,P.num,P.comment FROM Product P, Sellers S, Orders O WHERE P.sid = S.sid and O.pid = P.pid and O.cid = "+id;
        if(keyword.length() > 0) {
            sql = sql + " and pname LIKE '%" + keyword + "%'"; 
        }
        if(str_min.length() > 0){
            sql = sql + " and price >= " + minprice;
        }
        if(str_max.length() > 0){
            sql = sql + " and price <=" + maxprice;
        }
        if(str_pid.length() > 0){
            sql = sql + " and P.pid = " + pid;
        }
        if(sorttype.equals("价格从低到高")){
            sql = sql + " order by price ASC";
        }else if(sorttype.equals("价格从高到低")) {
             sql = sql + " order by price DESC";
        }else if(sorttype.equals("销量从低到高")) {
             sql = sql + " order by  P.sellnum ASC";
        }else if(sorttype.equals("销量从高到低")) {
             sql = sql + " order by  P.sellnum DESC";
        }
        
        try {
            all = this.daoproxy.findCorders(sql);
        } catch (Exception ex) {
            String message = ex.getMessage();
            int index = message.lastIndexOf(')');
            message = message.substring(index+1);
            JOptionPane.showMessageDialog(this, message+"\n请重新输入");
            return;
        }
        //
        DefaultTableModel dtm = (DefaultTableModel)C_query_jTable1.getModel();
        int row = dtm.getRowCount();
        for(int i = 0; i < row; ++i){
            dtm.removeRow(0);
        }
        row = all.size();
        for(int i = 0; i < row; ++i){
           Object[]rowData = {
               all.get(i).oid,
               all.get(i).pid,
               all.get(i).pname,
               all.get(i).price,
               all.get(i).buynum,
               all.get(i).sname,
               all.get(i).sum
           };
           dtm.addRow(rowData);
        }
    }//GEN-LAST:event_C_jButton_search1ActionPerformed

    private void C_query_jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C_query_jTable1MouseClicked
        // TODO add your handling code here:
        int row = C_query_jTable1.getSelectedRow();
        JOptionPane.showMessageDialog(this, row);
        Corders corders = all.get(row);
        EditOrder editOrder = new EditOrder();
        editOrder.setconf(this, corders);
        editOrder.setVisible(true);
    }//GEN-LAST:event_C_query_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cmain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C_jButton_Order;
    private javax.swing.JButton C_jButton_clear1;
    private javax.swing.JButton C_jButton_einfo;
    private javax.swing.JButton C_jButton_product;
    private javax.swing.JButton C_jButton_search;
    private javax.swing.JButton C_jButton_search1;
    private javax.swing.JComboBox<String> C_jComboBox_sort;
    private javax.swing.JComboBox<String> C_jComboBox_sort1;
    private javax.swing.JLabel C_jLabel_Oid;
    private javax.swing.JTextField C_jTextField_oid1;
    private javax.swing.JTextField C_jTextField_pid;
    private javax.swing.JTextField C_jTextField_pid1;
    private javax.swing.JTextField C_jTextField_pmax;
    private javax.swing.JTextField C_jTextField_pmax1;
    private javax.swing.JTextField C_jTextField_pmin;
    private javax.swing.JTextField C_jTextField_pmin1;
    private javax.swing.JTextField C_jTextField_pname;
    private javax.swing.JTextField C_jTextField_pname1;
    private javax.swing.JToggleButton C_jToggleButton_sort;
    private javax.swing.JTable C_query_jTable;
    private javax.swing.JTable C_query_jTable1;
    private javax.swing.JLabel L_Price;
    private javax.swing.JLabel L_Price1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Pname;
    private javax.swing.JLabel jLabel_Pname1;
    private javax.swing.JLabel jLabel_Pname2;
    private javax.swing.JLabel jLabel_Pname3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_Menu;
    private javax.swing.JPanel jPanel_Order;
    private javax.swing.JPanel jPanel_Product;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
