/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jiemian;

import Dao.Customers;
import Dao.Daoproxy;
import Dao.Sellers;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.runtime.logging.Logger;

/**
 *
 * @author zero
 */
public class Information extends javax.swing.JFrame {

    /**
     * Creates new form Information
     */
    String oldname, oldsex, oldphonenum, oldpassword, oldusrtype;
    int oldage;
    int id;
    String name, sex, phonenum, usrtype, password1, password2;
    int age;
    Daoproxy daoproxy;
    Customers parent1;
    Sellers parent2;
    public Information() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        R_jButton_register = new javax.swing.JButton();
        R_Lable_pid = new javax.swing.JLabel();
        R_Lable_password = new javax.swing.JLabel();
        R_jButton_cancle = new javax.swing.JButton();
        R_jPasswordField1 = new javax.swing.JPasswordField();
        R_Lable_password1 = new javax.swing.JLabel();
        R_Lable_phonenum = new javax.swing.JLabel();
        R_jPasswordField2 = new javax.swing.JPasswordField();
        R_jTextField_phonenum = new javax.swing.JTextField();
        R_jComboBox_Sex = new javax.swing.JComboBox<>();
        R_Lable_usertype = new javax.swing.JLabel();
        R_Lable_name1 = new javax.swing.JLabel();
        R_Lable_name2 = new javax.swing.JLabel();
        R_Lable_age = new javax.swing.JLabel();
        R_Lable_name = new javax.swing.JLabel();
        R_jTextField_age = new javax.swing.JTextField();
        R_jTextField_name = new javax.swing.JTextField();
        R_Lable_usrtype = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        R_jButton_register.setText("确认");
        R_jButton_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_jButton_registerActionPerformed(evt);
            }
        });

        R_Lable_pid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R_Lable_pid.setText("0");
        R_Lable_pid.setToolTipText("");

        R_Lable_password.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R_Lable_password.setText("密码:");
        R_Lable_password.setToolTipText("");

        R_jButton_cancle.setText("取消");
        R_jButton_cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_jButton_cancleActionPerformed(evt);
            }
        });

        R_jPasswordField1.setText("        ");
        R_jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_jPasswordField1ActionPerformed(evt);
            }
        });

        R_Lable_password1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R_Lable_password1.setText("密码:");
        R_Lable_password1.setToolTipText("");

        R_Lable_phonenum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R_Lable_phonenum.setText("手机:");
        R_Lable_phonenum.setToolTipText("");

        R_jPasswordField2.setText("        ");
        R_jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_jPasswordField2ActionPerformed(evt);
            }
        });

        R_jTextField_phonenum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        R_jTextField_phonenum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                R_jTextField_phonenumjTextFieldFocusGained_Rname(evt);
            }
        });

        R_jComboBox_Sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "男", "女" }));
        R_jComboBox_Sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_jComboBox_SexActionPerformed(evt);
            }
        });

        R_Lable_usertype.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R_Lable_usertype.setText("用户类型:");
        R_Lable_usertype.setToolTipText("");

        R_Lable_name1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R_Lable_name1.setText("性别:");
        R_Lable_name1.setToolTipText("");

        R_Lable_name2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R_Lable_name2.setText("用户id:");
        R_Lable_name2.setToolTipText("");

        R_Lable_age.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R_Lable_age.setText("年龄:");
        R_Lable_age.setToolTipText("");

        R_Lable_name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R_Lable_name.setText("用户名:");
        R_Lable_name.setToolTipText("");

        R_jTextField_age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        R_jTextField_age.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                R_jTextField_agejTextFieldFocusGained_Rname(evt);
            }
        });

        R_jTextField_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        R_jTextField_name.setText("必填");
        R_jTextField_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                R_jTextField_namejTextFieldFocusGained_Rname(evt);
            }
        });

        R_Lable_usrtype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R_Lable_usrtype.setText("类型");
        R_Lable_usrtype.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(R_Lable_name, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R_Lable_usertype, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(R_Lable_usrtype, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(R_Lable_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R_Lable_pid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(R_jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(R_Lable_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(R_Lable_phonenum, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(R_Lable_password, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(R_jComboBox_Sex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(R_Lable_age, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(R_jTextField_age, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(R_jPasswordField1)
                            .addComponent(R_jTextField_phonenum)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(R_jButton_register)
                        .addGap(40, 40, 40)
                        .addComponent(R_jButton_cancle)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(R_Lable_password1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(R_jPasswordField2)))
                .addGap(0, 77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R_Lable_usertype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R_Lable_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R_Lable_pid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R_Lable_usrtype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R_Lable_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R_jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R_Lable_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R_jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R_Lable_password1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R_jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R_Lable_phonenum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R_jTextField_phonenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(R_jTextField_age, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(R_jComboBox_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(R_Lable_age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(R_Lable_name1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R_jButton_register)
                    .addComponent(R_jButton_cancle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setconf(Daoproxy _daoproxy, int _id, String _oldname, String _oldsex, String _oldphonenum, String _oldpassword, String _usrtype, int _oldage, 
            Customers customers, Sellers sellers){
        daoproxy = _daoproxy;
        id = _id;
        oldname = _oldname;
        oldsex = _oldsex;
        oldphonenum = _oldphonenum;
        oldpassword = _oldpassword;
        oldusrtype = _usrtype;
        oldage = _oldage;
        parent1 = customers;
        parent2 = sellers;
        setinit();
    }
    public void setinit(){
      //  R_jComboBox_type.setEnabled(false);
        R_Lable_usrtype.setText(oldusrtype);
        
        R_jComboBox_Sex.setToolTipText(oldsex);
        R_jTextField_name.setText(oldname);
        R_jPasswordField1.setText("");
        R_jPasswordField2.setText("");
        R_jTextField_phonenum.setText(oldphonenum);
        R_jTextField_age.setText(String.valueOf(oldage));
        R_Lable_pid.setText(String.valueOf(id));
        
    }
    public boolean gettext(){
        usrtype = (String)R_Lable_usrtype.getText();
        
        name = R_jTextField_name.getText().trim();
        if(name.length() == 0){
            JOptionPane.showMessageDialog(null, "用户名不能为空");
            return false;
        }
        
        phonenum = R_jTextField_phonenum.getText().trim();
        sex = String.valueOf(R_jComboBox_Sex.getSelectedItem());
        password1 = R_jPasswordField1.getText();
        password2 = R_jPasswordField2.getText();
        String stringage;
        stringage = R_jTextField_age.getText().trim();
        try{
            age = Integer.valueOf(stringage);
        }catch(Exception e1){
            String message = e1.getMessage();
            int index = message.lastIndexOf(')');
            message = message.substring(index+1);
            JOptionPane.showMessageDialog(this, message+"\n请重新输入");
            return false;
        }

        
        if(!password1.equals(password2)){
            JOptionPane.showMessageDialog(null, "两次密码不一致");
            return false;
        }
        return true;
    }
    private void R_jButton_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_jButton_registerActionPerformed
        // TODO add your handling code here:

        if(!gettext()) {
            setinit();
            return;
        }
        if(usrtype.equals("消费者")){
            Customers customers;
            customers = new Customers(id, name, phonenum, sex, age, password1);
            try {
                boolean ok = daoproxy.doUpdatebyCid(customers);
                if(ok) {
                    JOptionPane.showMessageDialog(null, "修改成功");
                    customers.password = password1;
                    customers.cid = id;
                }
                else JOptionPane.showMessageDialog(null, "修改失败");
            } catch (Exception ex) {
                String message = ex.getMessage();
                int index = message.lastIndexOf(')');
                message = message.substring(index+1);
                JOptionPane.showMessageDialog(this, message+"\n请重新输入");
                setinit();
            }

        }
        else if(usrtype.equals("商家")){
            Sellers sellers;
            //  int sid, String sname, String phonenum, String sex, int age, String password, Collection<Product> product
            sellers = new Sellers(id, name, phonenum, sex, age, password1,null);
            try {
                boolean ok = daoproxy.doUpdatebySid(sellers);
                if(ok) {
                    JOptionPane.showMessageDialog(null, "修改成功");
                    parent2.password = password1;
                    sellers.sid = id;
                }
                else JOptionPane.showMessageDialog(null, "修改失败");
            } catch (Exception ex) {
                String message = ex.getMessage();
                int index = message.lastIndexOf(')');
                message = message.substring(index+1);
                JOptionPane.showMessageDialog(this, message+"\n请重新输入");
                setinit();
            }
        }
        this.setVisible(false);
    }//GEN-LAST:event_R_jButton_registerActionPerformed

    private void R_jButton_cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_jButton_cancleActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);

    }//GEN-LAST:event_R_jButton_cancleActionPerformed

    private void R_jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_jPasswordField1ActionPerformed

    private void R_jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_jPasswordField2ActionPerformed

    private void R_jTextField_phonenumjTextFieldFocusGained_Rname(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_R_jTextField_phonenumjTextFieldFocusGained_Rname
        // TODO add your handling code here:
    }//GEN-LAST:event_R_jTextField_phonenumjTextFieldFocusGained_Rname

    private void R_jComboBox_SexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_jComboBox_SexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_jComboBox_SexActionPerformed

    private void R_jTextField_agejTextFieldFocusGained_Rname(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_R_jTextField_agejTextFieldFocusGained_Rname
        // TODO add your handling code here:
    }//GEN-LAST:event_R_jTextField_agejTextFieldFocusGained_Rname

    private void R_jTextField_namejTextFieldFocusGained_Rname(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_R_jTextField_namejTextFieldFocusGained_Rname
        // TODO add your handling code here:
    }//GEN-LAST:event_R_jTextField_namejTextFieldFocusGained_Rname

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel R_Lable_age;
    private javax.swing.JLabel R_Lable_name;
    private javax.swing.JLabel R_Lable_name1;
    private javax.swing.JLabel R_Lable_name2;
    private javax.swing.JLabel R_Lable_password;
    private javax.swing.JLabel R_Lable_password1;
    private javax.swing.JLabel R_Lable_phonenum;
    private javax.swing.JLabel R_Lable_pid;
    private javax.swing.JLabel R_Lable_usertype;
    private javax.swing.JLabel R_Lable_usrtype;
    private javax.swing.JButton R_jButton_cancle;
    private javax.swing.JButton R_jButton_register;
    private javax.swing.JComboBox<String> R_jComboBox_Sex;
    private javax.swing.JPasswordField R_jPasswordField1;
    private javax.swing.JPasswordField R_jPasswordField2;
    private javax.swing.JTextField R_jTextField_age;
    private javax.swing.JTextField R_jTextField_name;
    private javax.swing.JTextField R_jTextField_phonenum;
    // End of variables declaration//GEN-END:variables
}
