package jiemian;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import Dao.Daoproxy;
import Dao.Managers;
import Dao.Customers;
import Dao.Sellers;
import java.awt.Container;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author zeroxf
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form test
     */
    Daoproxy daoproxy;
    String usrtype;
    Customers customers;
    Sellers sellers;
    Managers managers;
    JFrame frame;
    Register register;
    Cmain cmain;
    Smain smain;
    Mmain mmain;
    String password;
    public Login(Daoproxy daoproxy, JFrame frame) {
        super();
        this.daoproxy = new Daoproxy();
        this.frame = frame;
        register = new Register(this, frame);
        this.frame.add(register);
        this.setVisible(true);
        this.register.setVisible(false);
        mmain = null;
        smain = null;
        cmain = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_test_usrid = new javax.swing.JTextField();
        Label_usrid = new javax.swing.JLabel();
        Label_pwd = new javax.swing.JLabel();
        L_text_usr_type = new javax.swing.JComboBox<>();
        BN_Login = new javax.swing.JButton();
        L_text_password = new javax.swing.JPasswordField();
        BN_Register = new javax.swing.JButton();
        L_Label_usrtype = new javax.swing.JLabel();

        L_test_usrid.setText("请输入你的id");
        L_test_usrid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextUsernameFocusLost(evt);
            }
        });
        L_test_usrid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextUserMouseClicked(evt);
            }
        });

        Label_usrid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Label_usrid.setText("用户账号:");

        Label_pwd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Label_pwd.setText("密码:");

        L_text_usr_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "消费者", "商家", "管理员" }));

        BN_Login.setText("登录");
        BN_Login.setToolTipText("");
        BN_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BN_LoginActionPerformed(evt);
            }
        });

        L_text_password.setText("jPasswordField1");
        L_text_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                L_text_passwordFocusGained(evt);
            }
        });

        BN_Register.setText("注册");
        BN_Register.setToolTipText("");
        BN_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BN_RegisterActionPerformed(evt);
            }
        });

        L_Label_usrtype.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        L_Label_usrtype.setText("用户类型:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Label_usrid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(L_Label_usrtype, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Label_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_test_usrid, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_text_password, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_text_usr_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BN_Login)
                .addGap(18, 18, 18)
                .addComponent(BN_Register)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_text_usr_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Label_usrtype, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_usrid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_test_usrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_text_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BN_Login)
                    .addComponent(BN_Register))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents
        
    private void BN_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BN_LoginActionPerformed
        // TODO add your handling code here:
        customers = null;
        managers = null;
        sellers = null;
       
        String text_id = L_test_usrid.getText().trim();
        int usrid=0;
        try{
            usrid = Integer.valueOf(text_id).intValue();
        }catch(Exception e1){
            e1.printStackTrace();
            String message = e1.getMessage();
            int index = message.lastIndexOf(')');
            message = message.substring(index+1);
            JOptionPane.showMessageDialog(this, message+"\n请重新输入");
        }
        password = String.valueOf(L_text_password.getPassword());
        this.usrtype = (String) L_text_usr_type.getSelectedItem();

        
        try {
            customers =  daoproxy.findCustomers(usrid, password);
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(usrtype.equals("消费者")) {
             try {
                 customers =  daoproxy.findCustomers(usrid, password);
             } catch (Exception ex) {
                 Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
             }
             if(customers != null){
                 this.setVisible(false);
                 frame.setVisible(false);
               //  System.out.print(customers.phonenum);
               if(cmain == null) {
                   cmain = new Cmain();
                   
               }
               cmain.setconf(this, usrid, daoproxy);
               cmain.setVisible(true);
             }else{
                 JOptionPane.showMessageDialog(null, "用户名或密码错误");
             }
        }else if(usrtype.equals("商家")) {
            try {
                sellers = daoproxy.findSellers(usrid, password);
            } catch (Exception ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(sellers != null) {
                if(smain == null) {
                    smain = new Smain();
                }
                 this.setVisible(false);
                 frame.setVisible(false);
                 smain.setconf(this, usrid, daoproxy);
                 smain.setVisible(true);
            }else {
                JOptionPane.showMessageDialog(null, "用户名或密码错误");
            }
        }else if(usrtype.equals("管理员")){
            try {
                managers = daoproxy.findManagers(usrid, password);
            } catch (Exception ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
             if(managers != null) {
                mmain = new Mmain();
                this.setVisible(false);
                 frame.setVisible(false);
                 mmain.setconf(this, usrid, daoproxy);
                 mmain.setVisible(true);
            }else {
                JOptionPane.showMessageDialog(null, "用户名或密码错误");
            }
        }
        
    }//GEN-LAST:event_BN_LoginActionPerformed

    private void jTextUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextUserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUserMouseClicked

    private void jTextUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextUsernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUsernameFocusLost

    private void jTextUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextUsernameFocusGained
        // TODO add your handling code here:
       if(L_test_usrid.getText().equals("请输入你的id")) L_test_usrid.setText("");
      
    }//GEN-LAST:event_jTextUsernameFocusGained

    private void BN_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BN_RegisterActionPerformed
        // TODO add your handling code here:
        register.setVisible(true);
        register.setSize(400,400);
        frame.setSize(400,400);
        this.setVisible(false);
      //  register = new Register();
       // register.setVisible(true);
        
      //  register.setVisible(true);
    }//GEN-LAST:event_BN_RegisterActionPerformed

    private void L_text_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_L_text_passwordFocusGained
        // TODO add your handling code here:
        if(L_text_password.getText().trim().equals("jPasswordField1")){
            L_text_password.setText("");
        }
    }//GEN-LAST:event_L_text_passwordFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BN_Login;
    private javax.swing.JButton BN_Register;
    private javax.swing.JLabel L_Label_usrtype;
    private javax.swing.JTextField L_test_usrid;
    private javax.swing.JPasswordField L_text_password;
    private javax.swing.JComboBox<String> L_text_usr_type;
    private javax.swing.JLabel Label_pwd;
    private javax.swing.JLabel Label_usrid;
    // End of variables declaration//GEN-END:variables
}
