/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jiemian;

import Dao.Corders;


import Dao.Daoproxy;
import Dao.Product;
import Dao.Sellers;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zero
 */
public class Smain extends javax.swing.JFrame {

    /**
     * Creates new form Smain
     */
    Login parent;
    int id;
    Daoproxy daoproxy;
    Product product;
    AddProduct addproduct;
    Sellers sellers;
    public void setconf(Login _parent, int _id, Daoproxy _daoproxy){
        id = _id;
        parent = _parent;
        daoproxy = _daoproxy;
        sellers = new Sellers(id, null, null, null, 0, parent.password, null);
    }
    public Smain() {
         AddProduct addproduct = new AddProduct();
         
         addproduct.setVisible(false);
         initComponents();
         this.jPanel_Order.setVisible(false);
         this.jPanel_Product.setVisible(true);
         this.my_pro.setVisible(false);
         this.jPanel_Product.setVisible(true);
        this.jPanel_Order.setVisible(false);
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();// 设置table内容居中
        // tcr.setHorizontalAlignment(JLabel.CENTER);
        tcr.setHorizontalAlignment(SwingConstants.CENTER);// 这句和上句作用一样
        C_query_jTable.setDefaultRenderer(Object.class, tcr);
        C_query_jTable1.setDefaultRenderer(Object.class, tcr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        S_jButton_addproduct = new javax.swing.JButton();
        S_jButton_queryproduct = new javax.swing.JButton();
        S_jButton_queryorder = new javax.swing.JButton();
        S_jButton_Info = new javax.swing.JButton();
        query_pro = new javax.swing.JPanel();
        jPanel_Order = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        L_Price1 = new javax.swing.JLabel();
        C_jTextField_pmin1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        C_jTextField_pmax1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        C_jTextField_pname1 = new javax.swing.JTextField();
        jLabel_Pname2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel_Pname3 = new javax.swing.JLabel();
        C_jTextField_pid1 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        C_jButton_clear1 = new javax.swing.JButton();
        C_jButton_search1 = new javax.swing.JButton();
        C_jComboBox_sort1 = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        C_jLabel_Oid = new javax.swing.JLabel();
        C_jTextField_oid1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        C_query_jTable1 = new javax.swing.JTable();
        my_pro = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Q_jTable_product1 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Q_jTextField_Pname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Q_jTextField_Pid = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jPanel_Product = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        L_Price = new javax.swing.JLabel();
        C_jTextField_pmin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        C_jTextField_pmax = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        C_jTextField_pname = new javax.swing.JTextField();
        jLabel_Pname = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_Pname1 = new javax.swing.JLabel();
        C_jTextField_pid = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        C_jButton_search = new javax.swing.JButton();
        C_jComboBox_sort = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        C_query_jTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        S_jButton_addproduct.setText("添加商品");
        S_jButton_addproduct.setMaximumSize(new java.awt.Dimension(81, 46));
        S_jButton_addproduct.setMinimumSize(new java.awt.Dimension(81, 46));
        S_jButton_addproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_jButton_addproductActionPerformed(evt);
            }
        });
        jPanel1.add(S_jButton_addproduct);

        S_jButton_queryproduct.setText("我的商品");
        S_jButton_queryproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_jButton_queryproductActionPerformed(evt);
            }
        });
        jPanel1.add(S_jButton_queryproduct);

        S_jButton_queryorder.setText("我的订单");
        S_jButton_queryorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_jButton_queryorderActionPerformed(evt);
            }
        });
        jPanel1.add(S_jButton_queryorder);

        S_jButton_Info.setText("我的资料");
        S_jButton_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_jButton_InfoActionPerformed(evt);
            }
        });
        jPanel1.add(S_jButton_Info);

        query_pro.setLayout(new javax.swing.OverlayLayout(query_pro));

        L_Price1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        L_Price1.setText("价格:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("-");

        C_jTextField_pmax1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_jTextField_pmax1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(L_Price1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jTextField_pmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jTextField_pmax1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(L_Price1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(C_jTextField_pmin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(C_jTextField_pmax1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel_Pname2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Pname2.setText("商品名:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel_Pname2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C_jTextField_pname1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_jTextField_pname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Pname2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Pname3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Pname3.setText("商品id:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Pname3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jTextField_pid1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Pname3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_jTextField_pid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        C_jButton_clear1.setText("清零");
        C_jButton_clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_jButton_clear1ActionPerformed(evt);
            }
        });

        C_jButton_search1.setText("搜索");
        C_jButton_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_jButton_search1ActionPerformed(evt);
            }
        });

        C_jComboBox_sort1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "价格从低到高", "价格从高到低", "销量从低到高", "销量从高到低" }));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(C_jComboBox_sort1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jButton_clear1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jButton_search1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_jButton_clear1)
                    .addComponent(C_jButton_search1)
                    .addComponent(C_jComboBox_sort1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        C_jLabel_Oid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        C_jLabel_Oid.setText("订单号:");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(C_jLabel_Oid, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jTextField_oid1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_jLabel_Oid, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_jTextField_oid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        C_query_jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "订单号", "商品id", "商品", "价格", "数量", "买家", "总价"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        C_query_jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C_query_jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(C_query_jTable1);

        javax.swing.GroupLayout jPanel_OrderLayout = new javax.swing.GroupLayout(jPanel_Order);
        jPanel_Order.setLayout(jPanel_OrderLayout);
        jPanel_OrderLayout.setHorizontalGroup(
            jPanel_OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_OrderLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel_OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        jPanel_OrderLayout.setVerticalGroup(
            jPanel_OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_OrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        query_pro.add(jPanel_Order);

        Q_jTable_product1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "产品id", "商品名", "价格", "数量", "说明", "销量"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Q_jTable_product1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q_jTable_product1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Q_jTable_product1);

        clear.setText("清零");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel1.setText("商品名:");

        jLabel2.setText("商品id:");

        search.setText("搜索");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Q_jTextField_Pname, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Q_jTextField_Pid, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Q_jTextField_Pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Q_jTextField_Pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear)
                    .addComponent(search))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout my_proLayout = new javax.swing.GroupLayout(my_pro);
        my_pro.setLayout(my_proLayout);
        my_proLayout.setHorizontalGroup(
            my_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(my_proLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(my_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, my_proLayout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        my_proLayout.setVerticalGroup(
            my_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, my_proLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        query_pro.add(my_pro);

        L_Price.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        L_Price.setText("价格:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");

        C_jTextField_pmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_jTextField_pmaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(L_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C_jTextField_pmin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jTextField_pmax, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_jTextField_pmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_jTextField_pmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Pname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Pname.setText("商品名:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Pname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jTextField_pname, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Pname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(C_jTextField_pname))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Pname1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Pname1.setText("商品id:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Pname1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C_jTextField_pid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Pname1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_jTextField_pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton4.setText("清零");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        C_jButton_search.setText("搜索");
        C_jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_jButton_searchActionPerformed(evt);
            }
        });

        C_jComboBox_sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "价格从低到高", "价格从高到低", "销量从低到高", "销量从高到低" }));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(C_jComboBox_sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_jButton_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(C_jButton_search)
                    .addComponent(C_jComboBox_sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        C_query_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "商品id", "商品", "价格", "销量", "库存", "说明"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        C_query_jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C_query_jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(C_query_jTable);

        javax.swing.GroupLayout jPanel_ProductLayout = new javax.swing.GroupLayout(jPanel_Product);
        jPanel_Product.setLayout(jPanel_ProductLayout);
        jPanel_ProductLayout.setHorizontalGroup(
            jPanel_ProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProductLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel_ProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel_ProductLayout.setVerticalGroup(
            jPanel_ProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ProductLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        query_pro.add(jPanel_Product);

        jButton2.setText("注销");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(query_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(query_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void S_jButton_addproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_jButton_addproductActionPerformed
        // TODO add your handling code here:
        addproduct = new AddProduct();
        addproduct.setconf(this);
        addproduct.setVisible(true);
        
    }//GEN-LAST:event_S_jButton_addproductActionPerformed

    private void S_jButton_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_jButton_InfoActionPerformed
        // TODO add your handling code here:
        Information editinfo = new Information();
        
        try {
            sellers = daoproxy.findSellers(id, sellers.password);
        } catch (Exception ex) {
            Logger.getLogger(Smain.class.getName()).log(Level.SEVERE, null, ex);
            String message = ex.getMessage();
            int index = message.lastIndexOf(')');
            message = message.substring(index+1);
            JOptionPane.showMessageDialog(this, message);
            return ;
        }
        //Daoproxy _daoproxy, int _id, String _oldname, String _oldsex, String _oldphonenum, String _oldpassword, String _usrtype, int _oldage){
        editinfo.setconf(daoproxy, id, sellers.sname,sellers.sex, sellers.phonenum, sellers.password, "商家", sellers.age,null,sellers);
        editinfo.setVisible(true);
    }//GEN-LAST:event_S_jButton_InfoActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        Q_jTextField_Pid.setText("");
        Q_jTextField_Pname.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)Q_jTable_product1.getModel();
        int row = dtm.getRowCount();
        for(int i = 0; i < row; ++i){
            dtm.removeRow(0);
        }
        String str_pid = Q_jTextField_Pid.getText();
        Integer pid = -1;
        if(str_pid.length() > 0){
            try{
                pid = Integer.valueOf(str_pid.trim());
            }catch(Exception e1){
                String message = e1.getMessage();
                int index = message.lastIndexOf(')');
                message = message.substring(index+1);
                JOptionPane.showMessageDialog(this, message+"\n请重新输入");
                return;
            }
        }
        String pname = Q_jTextField_Pname.getText();
        pname = pname.replace(" ","");
        String sql = "select pid,pname,S.sid,price,comment,num,S.sname,sellnum FROM Product P Sellers S WHERE S.sid=P.sid and sid="+String.valueOf(id);
        if(pid != -1) sql = sql + " and pid="+ String.valueOf(pid);
        if(pname.length()>0) {
            sql = sql + " and pname LIKE '%"+pname + "%'";
        }
        sql = sql + ";";
      //  JOptionPane.showMessageDialog(this, sql);
        List<Product> all = null ;
        try {
            all = this.daoproxy.findProduct(sql);
        } catch (Exception ex) {
            Logger.getLogger(Smain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        row = all.size();
        for(int i = 0; i < all.size(); ++i){
           Object[]rowData = {
               all.get(i).pid,
               all.get(i).pname,
               all.get(i).price,
               all.get(i).num,
               all.get(i).comment
           };
           dtm.addRow(rowData);
        }
    }//GEN-LAST:event_searchActionPerformed
    
    private void Q_jTable_product1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q_jTable_product1MouseClicked
        // TODO add your handling code here:
        int row = Q_jTable_product1.getSelectedRow();
        int pid =(int) Q_jTable_product1.getValueAt(row,0);
        String pname = (String) Q_jTable_product1.getValueAt(row,1);
        double price = (double)Q_jTable_product1.getValueAt(row,2);
        int num = (int)Q_jTable_product1.getValueAt(row,3);
        String comment = (String)Q_jTable_product1.getValueAt(row,4);
    //    int _pid, String _pname, int _sid, double _price, String _comment, int _num)
        product = new Product(pid,pname,id,price,comment,num,null,0);
        EditProduct editProduct = new EditProduct();
        editProduct.setconf(this, product);
        editProduct.setVisible(true);
//        this.addproduct.setVisible(true);
        
    }//GEN-LAST:event_Q_jTable_product1MouseClicked

    private void S_jButton_queryproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_jButton_queryproductActionPerformed
        // TODO add your handling code here:
        this.jPanel_Product.setVisible(true);
        this.jPanel_Order.setVisible(false);
    }//GEN-LAST:event_S_jButton_queryproductActionPerformed

    private void S_jButton_queryorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_jButton_queryorderActionPerformed
        // TODO add your handling code here:
        this.jPanel_Product.setVisible(false);
        this.jPanel_Order.setVisible(true);
    }//GEN-LAST:event_S_jButton_queryorderActionPerformed

    private void C_jTextField_pmax1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_jTextField_pmax1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_jTextField_pmax1ActionPerformed

    private void C_jButton_clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_jButton_clear1ActionPerformed
        // TODO add your handling code here:
        C_jTextField_pname1.setText("");
         C_jTextField_oid1.setText("");
         C_jTextField_pmin1.setText("");
         C_jTextField_pmax1.setText("");
         C_jTextField_pid1.setText("");
         C_jComboBox_sort1.setSelectedIndex(0);
    }//GEN-LAST:event_C_jButton_clear1ActionPerformed

    private void C_jButton_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_jButton_search1ActionPerformed
        // TODO add your handling code here:
        String keyword = C_jTextField_pname1.getText().trim();
        String str_oid = C_jTextField_oid1.getText().trim();
        String str_min = C_jTextField_pmin1.getText().trim();
        String str_max = C_jTextField_pmax1.getText().trim();
        String str_pid = C_jTextField_pid1.getText().trim();
        String sorttype = (String)C_jComboBox_sort1.getSelectedItem();
        sorttype = sorttype.trim();
        double minprice = 0, maxprice = 1e10;
        int pid = 0;
        int oid = 0;
        try{
            if(str_min.length()>0)
            minprice = Double.valueOf(str_min);
            if(str_max.length()>0)
            maxprice = Double.valueOf(str_max);
            if(str_pid.length()>0)
            pid = Integer.valueOf(str_pid);
            if(str_oid.length()>0)
            oid = Integer.valueOf(str_oid);
        }catch(Exception ex){
            String message = ex.getMessage();
            int index = message.lastIndexOf(')');
        message = message.substring(index+1);
        JOptionPane.showMessageDialog(this, message+"\n请重新输入");
        return;
        }
        if(minprice < 0){
            minprice = 0;
            str_min = "0";
            C_jTextField_pmin.setText(str_min);
        }
        if(minprice > maxprice){
            str_max = "";
            C_jTextField_pmax.setText(str_max);
        }
        //   int _oid, int _pid, String _pname, int _sid,  double _price, int _buynum, String _sname, int _lastnum,double _sum
        String sql = "select oid,P.pid,pname,P.sid,price,O.num,C.cname,P.num,P.comment FROM Product P, Customers C, Orders O WHERE  O.pid = P.pid and O.cid = C.cid and P.sid =  "+id;
        if(keyword.length() > 0) {
            sql = sql + " and pname LIKE '%" + keyword + "%'";
        }
        if(str_min.length() > 0){
            sql = sql + " and price >= " + minprice;
        }
        if(str_max.length() > 0){
            sql = sql + " and price <=" + maxprice;
        }
        if(str_pid.length() > 0){
            sql = sql + " and P.pid = " + pid;
        }
        if(sorttype.equals("价格从低到高")){
            sql = sql + " order by price ASC";
        }else if(sorttype.equals("价格从高到低")) {
            sql = sql + " order by price DESC";
        }else if(sorttype.equals("销量从低到高")) {
            sql = sql + " order by  P.sellnum ASC";
        }else if(sorttype.equals("销量从高到低")) {
            sql = sql + " order by  P.sellnum DESC";
        }
        List<Corders> all = null ;
        try {
            all = this.daoproxy.findCorders(sql);
        } catch (Exception ex) {
            String message = ex.getMessage();
            int index = message.lastIndexOf(')');
        message = message.substring(index+1);
        JOptionPane.showMessageDialog(this, message+"\n请重新输入");
        return;
        }
        //
        DefaultTableModel dtm = (DefaultTableModel)C_query_jTable1.getModel();
        int row = dtm.getRowCount();
        for(int i = 0; i < row; ++i){
            dtm.removeRow(0);
        }
        row = all.size();
        for(int i = 0; i < row; ++i){
            Object[]rowData = {
                all.get(i).oid,
                all.get(i).pid,
                all.get(i).pname,
                all.get(i).price,
                all.get(i).buynum,
                all.get(i).sname,
                all.get(i).sum
            };
            dtm.addRow(rowData);
        }
    }//GEN-LAST:event_C_jButton_search1ActionPerformed

    private void C_query_jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C_query_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_C_query_jTable1MouseClicked

    private void C_jTextField_pmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_jTextField_pmaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_jTextField_pmaxActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        C_jTextField_pid.setText("");
        C_jTextField_pmax.setText("");
        C_jTextField_pmin.setText("");
        C_jTextField_pname.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void C_jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_jButton_searchActionPerformed
        // TODO add your handling code here:
        String keyword = C_jTextField_pname.getText().trim();
        String str_min = C_jTextField_pmin.getText().trim();
        String str_max = C_jTextField_pmax.getText().trim();
        String str_pid = C_jTextField_pid.getText().trim();
        String sorttype = (String)C_jComboBox_sort.getSelectedItem();
        sorttype = sorttype.trim();
        double minprice = 0, maxprice = 1e10;
        int pid = 0;
        try{
            if(str_min.length()>0)
            minprice = Double.valueOf(str_min);
            if(str_max.length()>0)
            maxprice = Double.valueOf(str_max);
            if(str_pid.length()>0)
            pid = Integer.valueOf(str_pid);
        }catch(Exception ex){
            String message = ex.getMessage();
            int index = message.lastIndexOf(')');
        message = message.substring(index+1);
        JOptionPane.showMessageDialog(this, message+"\n请重新输入");
        return;
        }
        if(minprice < 0){
            minprice = 0;
            str_min = "0";
            C_jTextField_pmin.setText(str_min);
        }
        if(minprice > maxprice){
            str_max = "";
            C_jTextField_pmax.setText(str_max);
        }

        String sql = "select pid,pname,P.sid,price,comment,num,S.sname,P.sellnum FROM Product P, Sellers S WHERE P.sid = S.sid and P.sid = "+id;
        if(keyword.length() > 0) {
            sql = sql + " and pname LIKE '%" + keyword + "%'";
        }
        if(str_min.length() > 0){
            sql = sql + " and price >= " + minprice;
        }
        if(str_max.length() > 0){
            sql = sql + "and price <=" + maxprice;
        }
        if(str_pid.length() > 0){
            sql = sql + " and pid = " + pid;
        }
        if(sorttype.equals("价格从低到高")){
            sql = sql + " order by price ASC";
        }else if(sorttype.equals("价格从高到低")) {
            sql = sql + " order by price DESC";
        }else if(sorttype.equals("销量从低到高")) {
            sql = sql + " order by  P.sellnum ASC";
        }else if(sorttype.equals("销量从高到低")) {
            sql = sql + " order by  P.sellnum DESC";
        }
        List<Product> all = null ;
        try {
            all = this.daoproxy.findProduct(sql);
        } catch (Exception ex) {
            String message = ex.getMessage();
            int index = message.lastIndexOf(')');
        message = message.substring(index+1);
        JOptionPane.showMessageDialog(this, message+"\n请重新输入");
        return;
        }

        //
        DefaultTableModel dtm = (DefaultTableModel)C_query_jTable.getModel();
        int row = dtm.getRowCount();
        for(int i = 0; i < row; ++i){
            dtm.removeRow(0);
        }
        row = all.size();
        for(int i = 0; i < row; ++i){
            Object[]rowData = {
                all.get(i).pid,
                all.get(i).pname,
                all.get(i).price,
                all.get(i).sellnum,
                all.get(i).num,
                all.get(i).comment,
              //  all.get(i).sname,
               
                 
            };
            dtm.addRow(rowData);
        }
    }//GEN-LAST:event_C_jButton_searchActionPerformed
    public void initsearch(){
        C_jButton_searchActionPerformed(null);
    }
    private void C_query_jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C_query_jTableMouseClicked
        // TODO add your handling code here:
        int row = C_query_jTable.getSelectedRow();
        int pid =(int) C_query_jTable.getValueAt(row,0);
        String pname = (String) C_query_jTable.getValueAt(row,1);
        double price = (double)C_query_jTable.getValueAt(row,2);
        int num = (int)C_query_jTable.getValueAt(row,4);
        String comment = (String)C_query_jTable.getValueAt(row,5);
  // int _pid, String _pname, int _sid, double _price, String _comment, int _num, String _sname, int _sellnum)
        product = new Product(pid,pname,id,price,comment,num,null,0);
        EditProduct editProduct = new EditProduct();
        editProduct.setconf(this, product);
        editProduct.setVisible(true);
    }//GEN-LAST:event_C_query_jTableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.parent.setVisible(true);
        this.parent.frame.setVisible(true);
        this.parent.setinit();
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Smain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Smain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Smain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Smain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Smain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C_jButton_clear1;
    private javax.swing.JButton C_jButton_search;
    private javax.swing.JButton C_jButton_search1;
    private javax.swing.JComboBox<String> C_jComboBox_sort;
    private javax.swing.JComboBox<String> C_jComboBox_sort1;
    private javax.swing.JLabel C_jLabel_Oid;
    private javax.swing.JTextField C_jTextField_oid1;
    private javax.swing.JTextField C_jTextField_pid;
    private javax.swing.JTextField C_jTextField_pid1;
    private javax.swing.JTextField C_jTextField_pmax;
    private javax.swing.JTextField C_jTextField_pmax1;
    private javax.swing.JTextField C_jTextField_pmin;
    private javax.swing.JTextField C_jTextField_pmin1;
    private javax.swing.JTextField C_jTextField_pname;
    private javax.swing.JTextField C_jTextField_pname1;
    private javax.swing.JTable C_query_jTable;
    private javax.swing.JTable C_query_jTable1;
    private javax.swing.JLabel L_Price;
    private javax.swing.JLabel L_Price1;
    private javax.swing.JTable Q_jTable_product1;
    private javax.swing.JTextField Q_jTextField_Pid;
    private javax.swing.JTextField Q_jTextField_Pname;
    private javax.swing.JButton S_jButton_Info;
    private javax.swing.JButton S_jButton_addproduct;
    private javax.swing.JButton S_jButton_queryorder;
    private javax.swing.JButton S_jButton_queryproduct;
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Pname;
    private javax.swing.JLabel jLabel_Pname1;
    private javax.swing.JLabel jLabel_Pname2;
    private javax.swing.JLabel jLabel_Pname3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_Order;
    private javax.swing.JPanel jPanel_Product;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel my_pro;
    private javax.swing.JPanel query_pro;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
